name: Lint pull request title

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

## Pattern to match strings as follows:
# ‚ú® feature(ui): Add `Button` component.
# ^  ^    ^    ^
# |  |    |    |__ Subject
# |  |    |_______ Scope
# |  |____________ Type
# |_______________ Emoji (for the related type)

jobs:
  main:
    runs-on: ubuntu-latest
    name: lint
    steps:
      - name: Validate PR title
        id: lint_pr_title
        uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          headerPattern: '^(\u00a9|\u00ae|[\u2000-\u3300]|\ud83c[\ud000-\udfff]|\ud83d[\ud000-\udfff]|\ud83e[\ud000-\udfff]|:\w*:) (\w*)(?:\(([\w\$\.\-\* ]*)\))?\: (.*)$'
          headerPatternCorrespondence: emoji, type, scope, subject
          types: |
            build
            chore
            ci
            docs
            feat
            fix
            perf
            refactor
            revert
            style
            test
            wip

      - uses: marocchino/sticky-pull-request-comment@v2
        # When the previous steps fails, the workflow would stop. By adding this
        # condition you can continue the execution with the populated error message.
        if: always() && (steps.lint_pr_title.outputs.error_message != null)
        with:
          header: pr-title-lint-error
          message: |
            Hey there and thank you for opening this pull request! üëãüèº

            We require pull request titles to be formatted as follows:
            ```
            ‚ú® feature(ui): Add `Button` component.
            ^  ^    ^    ^
            |  |    |    |__ Subject
            |  |    |_______ Scope
            |  |____________ Type
            |_______________ Emoji (for the related type)
            ```

            The current title does not match this format.
            <details>
              <summary>Error details üëÄ</summary>
              
              ```
              ${{ steps.lint_pr_title.outputs.error_message }}
              ```
            </details>

      # Delete a previous comment when the issue has been resolved
      - if: ${{ steps.lint_pr_title.outputs.error_message == null }}
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: pr-title-lint-error
          delete: true
